add events info and LastEvent command
jooby-dev/jooby-docs pull request #6
Opened 2023-04-07 13:42 UTC by DarkPark

2023-04-07 15:57 UTC, DeadByElpy requested changes

2023-04-07 15:57 UTC, DeadByElpy commented on docs/commands/uplink/LastEvent.md
> +>  `1`  | byte | [sequence number](#sequence-number-1)
at file only 1 header with `sequence-number` anchor

2023-04-07 18:35 UTC, DarkPark commented on docs/commands/uplink/LastEvent.md
> +>  `1`  | byte | [sequence number](#sequence-number-1)
fixed

2023-04-08 08:34 UTC, DeadByElpy approved these changes

2023-04-08 08:34 UTC, merged